sudo: required
language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - pip3 install -r requirements.txt

script:
  - pytest
  - docker build -t antoniomg89/project-z .
  - docker tag antoniomg89/project-z registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    #docker push antoniomg89/project-z-iv;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
branch: master
